In [ ]:
%pip install kagglehub pandas scikit-learn pyarrow
# fastparquet

In [3]:
import pandas as pd

# Load the dataset
data = pd.read_csv("/Users/b/Projects/_DeepLearning.AI/C4/ML/Kaggle/customer_churn/customer_churn_dataset-training-master.csv")

In [4]:
# Inspect it
data.shape

(440833, 12)

In [5]:
data.head(5)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [6]:
data.describe()
# total spend is 1 more than the 440833 in total rows meaning each column has 1 null value.

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000,440832.000000
mean,225398.667955,39.373153,31.256336,15.807494,3.604437,12.965722,631.616223,14.480868,0.567107
std,129531.918550,12.442369,17.255727,8.586242,3.070218,8.258063,240.803001,8.596208,0.495477
min,2.000000,18.000000,1.000000,1.000000,0.000000,0.000000,100.000000,1.000000,0.000000
25%,113621.750000,29.000000,16.000000,9.000000,1.000000,6.000000,480.000000,7.000000,0.000000
50%,226125.500000,39.000000,32.000000,16.000000,3.000000,12.000000,661.000000,14.000000,1.000000
75%,337739.250000,48.000000,46.000000,23.000000,6.000000,19.000000,830.000000,22.000000,1.000000
max,449999.000000,65.000000,60.000000,30.000000,10.000000,30.000000,1000.000000,30.000000,1.000000

In [7]:
# Show amount of null cells in each column
data.isnull().sum()

CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [8]:
# Show the entire row of missing entries
data[data['CustomerID'].isnull()]

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
199295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Drop Null amounts
data = data.dropna()

In [10]:
for col in ['Subscription Type','Contract Length']:
    print(col)
    print(data[col].value_counts(normalize=True))
    print('\n')

Subscription Type
Subscription Type
Standard    0.338288
Premium     0.337267
Basic       0.324446
Name: proportion, dtype: float64


Contract Length
Contract Length
Annual       0.401963
Quarterly    0.400447
Monthly      0.197590
Name: proportion, dtype: float64

In [12]:
features = data.iloc[:,0:-1]

In [13]:
labels = data.iloc[:,-1]

In [14]:
features.head(5)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0

In [ ]:
labels.head(5)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features,
                 labels,
                 test_size=0.2,
                 random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
numerical_columns = ['Age','Tenure','Usage Frequency','Support Calls',
                     'Payment Delay','Total Spend',
                     'Last Interaction']

In [ ]:
X_train_numerical = X_train[numerical_columns]

In [ ]:
#scaler.fit() computes mean & StdDev of each column
#scaler.transform() uses mean & StdDev to scale values of each column
scaler = StandardScaler()

In [ ]:
scaler.fit(X_train_numerical)

In [ ]:
X_train_scaled = scaler.transform(X_train_numerical)

In [ ]:
X_train_scaled_df = pd.DataFrame(data=X_train_scaled,
                                 index=X_train.index,
                                 columns=numerical_columns)

In [ ]:
X_train_scaled_df.head(5)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
categorical_columns = ['Subscription Type', 'Contract Length']

In [ ]:
X_train_categorical = X_train[categorical_columns]

In [ ]:
encoder = OneHotEncoder()

In [ ]:
# encoder.fit():
# 1. checks unique values within each category
# 2. prepares labels of output column
encoder.fit(X_train_categorical)

In [ ]:
X_train_encoded = encoder.transform(X_train_categorical)

In [ ]:
print(type(X_train_encoded))

In [ ]:
print(X_train_encoded)

In [ ]:
X_train_encoded.todense()

In [ ]:
encoder.get_feature_names_out()

In [ ]:
X_train_encoded_df = pd.DataFrame(X_train_encoded.todense(),
                                  index=X_train.index,
                                  columns= encoder.get_feature_names_out())

In [ ]:
X_train_encoded_df.head(10)

In [ ]:
X_train_transf = pd.concat([X_train['CustomerID'],
                            X_train_scaled_df,
                            X_train_encoded_df], axis=1)

In [ ]:
X_train_transf.head(5)

In [ ]:
#scaling the numerical columns in the testing set
X_test_scaled = scaler.transform(X_test[numerical_columns])

In [ ]:
# scaling the numerical columns in the testing set
X_test_scaled = scaler.transform(X_test[numerical_columns])
X_test_scaled_df = pd.DataFrame(data = X_test_scaled,
                                index=X_test.index,
                                columns=numerical_columns)

In [ ]:
# encoding the categorical columns in testing set
X_test_encoded = encoder.transform(X_test[categorical_columns]) 
X_test_encoded_df = pd.DataFrame(data=X_test_encoded.todense(),
                                 index=X_test.index,
                                 columns= encoder.get_feature_names_out())

In [ ]:
# concat the two DataFrames
X_test_trans = pd.concat([X_test['CustomerID'],
                          X_test_scaled_df,
                          X_test_encoded_df], axis=1)

In [ ]:
X_test_trans.head(5)

In [ ]:
X_train_transf.to_parquet("train.parquet")
X_test_trans.to_parquet("test.parquet")